cat FramebufferObject.cpp emptyline.txt > FramebufferObject.cpp2
cat FramebufferObject.h emptyline.txt > FramebufferObject.h2
cat gpgpuContext.cpp emptyline.txt > gpgpuContext.cpp2
cat init.cpp emptyline.txt > init.cpp2
cat ShaderProgramManager.cpp emptyline.txt > ShaderProgramManager.cpp2
cat ShaderProgramManager.h emptyline.txt > ShaderProgramManager.h2
cat SoXipBindTextures.cpp emptyline.txt > SoXipBindTextures.cpp2
cat SoXipBindTextures.cpp.old emptyline.txt > SoXipBindTextures.cpp.old2
cat SoXipBindTextures.h emptyline.txt > SoXipBindTextures.h2
cat SoXipBindTextures.h.old emptyline.txt > SoXipBindTextures.h.old2
cat SoXipBufferMask.cpp emptyline.txt > SoXipBufferMask.cpp2
cat SoXipBufferMaskElement.cpp emptyline.txt > SoXipBufferMaskElement.cpp2
cat SoXipBufferMask.h emptyline.txt > SoXipBufferMask.h2
cat SoXipCaptureImage.cpp emptyline.txt > SoXipCaptureImage.cpp2
cat SoXipClearBuffer.cpp emptyline.txt > SoXipClearBuffer.cpp2
cat SoXipClearBuffer.h emptyline.txt > SoXipClearBuffer.h2
cat SoXipClearFbo.cpp emptyline.txt > SoXipClearFbo.cpp2
cat SoXipClearFbo.h emptyline.txt > SoXipClearFbo.h2
cat SoXipCube.cpp emptyline.txt > SoXipCube.cpp2
cat SoXipCube.h emptyline.txt > SoXipCube.h2
cat SoXipDecomposeMFInt32.cpp emptyline.txt > SoXipDecomposeMFInt32.cpp2
cat SoXipDecomposeMFInt32.h emptyline.txt > SoXipDecomposeMFInt32.h2
cat SoXipDepthTest.cpp emptyline.txt > SoXipDepthTest.cpp2
cat SoXipDepthTestElement.cpp emptyline.txt > SoXipDepthTestElement.cpp2
cat SoXipDepthTest.h emptyline.txt > SoXipDepthTest.h2
cat SoXipDrawBuffersElement.cpp emptyline.txt > SoXipDrawBuffersElement.cpp2
cat SoXipDrawImage.cpp emptyline.txt > SoXipDrawImage.cpp2
cat SoXipDrawQuad.cpp emptyline.txt > SoXipDrawQuad.cpp2
cat SoXipFboAttachColor3D.cpp emptyline.txt > SoXipFboAttachColor3D.cpp2
cat SoXipFboAttachColor3D.h emptyline.txt > SoXipFboAttachColor3D.h2
cat SoXipFboAttachColor.cpp emptyline.txt > SoXipFboAttachColor.cpp2
cat SoXipFboAttachColor.h emptyline.txt > SoXipFboAttachColor.h2
cat SoXipFboAttachDepth3D.cpp emptyline.txt > SoXipFboAttachDepth3D.cpp2
cat SoXipFboAttachDepth3D.h emptyline.txt > SoXipFboAttachDepth3D.h2
cat SoXipFboAttachDepth.cpp emptyline.txt > SoXipFboAttachDepth.cpp2
cat SoXipFboAttachDepth.h emptyline.txt > SoXipFboAttachDepth.h2
cat SoXipFbo.cpp emptyline.txt > SoXipFbo.cpp2
cat SoXipFboElement.cpp emptyline.txt > SoXipFboElement.cpp2
cat SoXipFbo.h emptyline.txt > SoXipFbo.h2
cat SoXipFramebufferElement.cpp emptyline.txt > SoXipFramebufferElement.cpp2
cat SoXipFramebufferFlip.cpp emptyline.txt > SoXipFramebufferFlip.cpp2
cat SoXipFramebufferGroup.cpp emptyline.txt > SoXipFramebufferGroup.cpp2
cat SoXipFramebufferGroup.h emptyline.txt > SoXipFramebufferGroup.h2
cat SoXipFrameRate.cpp emptyline.txt > SoXipFrameRate.cpp2
cat SoXipGetTransform.cpp emptyline.txt > SoXipGetTransform.cpp2
cat SoXipGlowElement.cpp emptyline.txt > SoXipGlowElement.cpp2
cat SoXipGLSLPrograms.cpp emptyline.txt > SoXipGLSLPrograms.cpp2
cat SoXipGLSLPrograms.h emptyline.txt > SoXipGLSLPrograms.h2
cat SoXipGLSLShaderProgramElement.cpp emptyline.txt > SoXipGLSLShaderProgramElement.cpp2
cat SoXipGLSLUseProgram.cpp emptyline.txt > SoXipGLSLUseProgram.cpp2
cat SoXipGLSLUseProgram.h emptyline.txt > SoXipGLSLUseProgram.h2
cat SoXipGLStringMarker.cpp emptyline.txt > SoXipGLStringMarker.cpp2
cat SoXipGLStringMarker.h emptyline.txt > SoXipGLStringMarker.h2
cat SoXipLoadShaders.cpp emptyline.txt > SoXipLoadShaders.cpp2
cat SoXipLoadShaders.h emptyline.txt > SoXipLoadShaders.h2
cat SoXipLogGLState.cpp emptyline.txt > SoXipLogGLState.cpp2
cat SoXipLogGLState.h emptyline.txt > SoXipLogGLState.h2
cat SoXipLutTexture.cpp emptyline.txt > SoXipLutTexture.cpp2
cat SoXipLutTexture.h emptyline.txt > SoXipLutTexture.h2
cat SoXipMultiplyMatrices.cpp emptyline.txt > SoXipMultiplyMatrices.cpp2
cat SoXipOffscreenRenderer.cpp emptyline.txt > SoXipOffscreenRenderer.cpp2
cat SoXipOpenGLError.cpp emptyline.txt > SoXipOpenGLError.cpp2
cat SoXipOpenGLError.h emptyline.txt > SoXipOpenGLError.h2
cat SoXipPingPong.cpp emptyline.txt > SoXipPingPong.cpp2
cat SoXipPingPongFlip.cpp emptyline.txt > SoXipPingPongFlip.cpp2
cat SoXipPingPongFlip.h emptyline.txt > SoXipPingPongFlip.h2
cat SoXipPingPong.h emptyline.txt > SoXipPingPong.h2
cat SoXipSetTransform.cpp emptyline.txt > SoXipSetTransform.cpp2
cat SoXipShaderProgramElement.cpp emptyline.txt > SoXipShaderProgramElement.cpp2
cat SoXipTextureUnit.cpp emptyline.txt > SoXipTextureUnit.cpp2
cat SoXipTextureUnit.h emptyline.txt > SoXipTextureUnit.h2
cat SoXipTransparentGeometryRenderer.cpp emptyline.txt > SoXipTransparentGeometryRenderer.cpp2
cat SoXipTransparentGeometryRenderer.h emptyline.txt > SoXipTransparentGeometryRenderer.h2
cat SoXipUniformVariable.cpp emptyline.txt > SoXipUniformVariable.cpp2
cat SoXipUniformVariable.h emptyline.txt > SoXipUniformVariable.h2
