cat geomutils.h ../core/emptyline.txt > geomutils.h2
cat SbXipMarkerShapes.h ../core/emptyline.txt > SbXipMarkerShapes.h2
cat SbXipPlot2LegendInfo.h ../core/emptyline.txt > SbXipPlot2LegendInfo.h2
cat SoXipEditableShape.h ../core/emptyline.txt > SoXipEditableShape.h2
cat SoXipEditText2.h ../core/emptyline.txt > SoXipEditText2.h2
cat SoXipEllipse.h ../core/emptyline.txt > SoXipEllipse.h2
cat SoXipFontTypeElement.h ../core/emptyline.txt > SoXipFontTypeElement.h2
cat SoXipHandlerShape.h ../core/emptyline.txt > SoXipHandlerShape.h2
cat SoXipImageTextColorElement.h ../core/emptyline.txt > SoXipImageTextColorElement.h2
cat SoXipManipulableShape.h ../core/emptyline.txt > SoXipManipulableShape.h2
cat SoXipOverlayColor.h ../core/emptyline.txt > SoXipOverlayColor.h2
cat SoXipOverlayElement.h ../core/emptyline.txt > SoXipOverlayElement.h2
cat SoXipOverlayManipBase.h ../core/emptyline.txt > SoXipOverlayManipBase.h2
cat SoXipOverlayManipulatedElement.h ../core/emptyline.txt > SoXipOverlayManipulatedElement.h2
cat SoXipPlot2AreaElement.h ../core/emptyline.txt > SoXipPlot2AreaElement.h2
cat SoXipPlot2Element.h ../core/emptyline.txt > SoXipPlot2Element.h2
cat SoXipShape.h ../core/emptyline.txt > SoXipShape.h2
cat SoXipSubShape.h ../core/emptyline.txt > SoXipSubShape.h2
cat SoXipText2.h ../core/emptyline.txt > SoXipText2.h2
cat xipivoverlay.h ../core/emptyline.txt > xipivoverlay.h2
cat XipOverlayUtils.h ../core/emptyline.txt > XipOverlayUtils.h2
cat XipPrimitiveDraw.h ../core/emptyline.txt > XipPrimitiveDraw.h2
