mv geomutils.h2 geomutils.h
mv SbXipMarkerShapes.h2 SbXipMarkerShapes.h
mv SbXipPlot2LegendInfo.h2 SbXipPlot2LegendInfo.h
mv SoXipEditableShape.h2 SoXipEditableShape.h
mv SoXipEditText2.h2 SoXipEditText2.h
mv SoXipEllipse.h2 SoXipEllipse.h
mv SoXipFontTypeElement.h2 SoXipFontTypeElement.h
mv SoXipHandlerShape.h2 SoXipHandlerShape.h
mv SoXipImageTextColorElement.h2 SoXipImageTextColorElement.h
mv SoXipManipulableShape.h2 SoXipManipulableShape.h
mv SoXipOverlayColor.h2 SoXipOverlayColor.h
mv SoXipOverlayElement.h2 SoXipOverlayElement.h
mv SoXipOverlayManipBase.h2 SoXipOverlayManipBase.h
mv SoXipOverlayManipulatedElement.h2 SoXipOverlayManipulatedElement.h
mv SoXipPlot2AreaElement.h2 SoXipPlot2AreaElement.h
mv SoXipPlot2Element.h2 SoXipPlot2Element.h
mv SoXipShape.h2 SoXipShape.h
mv SoXipSubShape.h2 SoXipSubShape.h
mv SoXipText2.h2 SoXipText2.h
mv xipivoverlay.h2 xipivoverlay.h
mv XipOverlayUtils.h2 XipOverlayUtils.h
mv XipPrimitiveDraw.h2 XipPrimitiveDraw.h
