mv SbItkNodeContainer.h2 SbItkNodeContainer.h
mv SoItkDataArray.h2 SoItkDataArray.h
mv SoItkDataDecorator.h2 SoItkDataDecorator.h
mv SoItkDataImage.h2 SoItkDataImage.h
mv SoItkDataImageMetric.h2 SoItkDataImageMetric.h
mv SoItkDataInterpolator.h2 SoItkDataInterpolator.h
mv SoItkDataMatrix.h2 SoItkDataMatrix.h
mv SoItkDataNeighborhood.h2 SoItkDataNeighborhood.h
mv SoItkDataOptimizer.h2 SoItkDataOptimizer.h
mv SoItkDataPointSet.h2 SoItkDataPointSet.h
mv SoItkDataTransform.h2 SoItkDataTransform.h
mv SoItkMFDataImage.h2 SoItkMFDataImage.h
mv SoItkSFDataArray.h2 SoItkSFDataArray.h
mv SoItkSFDataDecorator.h2 SoItkSFDataDecorator.h
mv SoItkSFDataImage.h2 SoItkSFDataImage.h
mv SoItkSFDataImageMetric.h2 SoItkSFDataImageMetric.h
mv SoItkSFDataInterpolator.h2 SoItkSFDataInterpolator.h
mv SoItkSFDataMatrix.h2 SoItkSFDataMatrix.h
mv SoItkSFDataNeighborhood.h2 SoItkSFDataNeighborhood.h
mv SoItkSFDataOptimizer.h2 SoItkSFDataOptimizer.h
mv SoItkSFDataPointSet.h2 SoItkSFDataPointSet.h
mv SoItkSFDataTransform.h2 SoItkSFDataTransform.h
mv SoItkSFNodeContainer.h2 SoItkSFNodeContainer.h
mv SoItkUtils.h2 SoItkUtils.h
mv xipivitk.h2 xipivitk.h
