cat SbItkNodeContainer.h ../core/emptyline.txt > SbItkNodeContainer.h2
cat SoItkDataArray.h ../core/emptyline.txt > SoItkDataArray.h2
cat SoItkDataDecorator.h ../core/emptyline.txt > SoItkDataDecorator.h2
cat SoItkDataImage.h ../core/emptyline.txt > SoItkDataImage.h2
cat SoItkDataImageMetric.h ../core/emptyline.txt > SoItkDataImageMetric.h2
cat SoItkDataInterpolator.h ../core/emptyline.txt > SoItkDataInterpolator.h2
cat SoItkDataMatrix.h ../core/emptyline.txt > SoItkDataMatrix.h2
cat SoItkDataNeighborhood.h ../core/emptyline.txt > SoItkDataNeighborhood.h2
cat SoItkDataOptimizer.h ../core/emptyline.txt > SoItkDataOptimizer.h2
cat SoItkDataPointSet.h ../core/emptyline.txt > SoItkDataPointSet.h2
cat SoItkDataTransform.h ../core/emptyline.txt > SoItkDataTransform.h2
cat SoItkMFDataImage.h ../core/emptyline.txt > SoItkMFDataImage.h2
cat SoItkSFDataArray.h ../core/emptyline.txt > SoItkSFDataArray.h2
cat SoItkSFDataDecorator.h ../core/emptyline.txt > SoItkSFDataDecorator.h2
cat SoItkSFDataImage.h ../core/emptyline.txt > SoItkSFDataImage.h2
cat SoItkSFDataImageMetric.h ../core/emptyline.txt > SoItkSFDataImageMetric.h2
cat SoItkSFDataInterpolator.h ../core/emptyline.txt > SoItkSFDataInterpolator.h2
cat SoItkSFDataMatrix.h ../core/emptyline.txt > SoItkSFDataMatrix.h2
cat SoItkSFDataNeighborhood.h ../core/emptyline.txt > SoItkSFDataNeighborhood.h2
cat SoItkSFDataOptimizer.h ../core/emptyline.txt > SoItkSFDataOptimizer.h2
cat SoItkSFDataPointSet.h ../core/emptyline.txt > SoItkSFDataPointSet.h2
cat SoItkSFDataTransform.h ../core/emptyline.txt > SoItkSFDataTransform.h2
cat SoItkSFNodeContainer.h ../core/emptyline.txt > SoItkSFNodeContainer.h2
cat SoItkUtils.h ../core/emptyline.txt > SoItkUtils.h2
cat xipivitk.h ../core/emptyline.txt > xipivitk.h2
