perl -pe 's/Fields/fields/g' < SbItkNodeContainer.h > SbItkNodeContainer.h2
perl -pe 's/Fields/fields/g' < SoItkDataArray.h > SoItkDataArray.h2
perl -pe 's/Fields/fields/g' < SoItkDataDecorator.h > SoItkDataDecorator.h2
perl -pe 's/Fields/fields/g' < SoItkDataImage.h > SoItkDataImage.h2
perl -pe 's/Fields/fields/g' < SoItkDataImageMetric.h > SoItkDataImageMetric.h2
perl -pe 's/Fields/fields/g' < SoItkDataInterpolator.h > SoItkDataInterpolator.h2
perl -pe 's/Fields/fields/g' < SoItkDataMatrix.h > SoItkDataMatrix.h2
perl -pe 's/Fields/fields/g' < SoItkDataNeighborhood.h > SoItkDataNeighborhood.h2
perl -pe 's/Fields/fields/g' < SoItkDataOptimizer.h > SoItkDataOptimizer.h2
perl -pe 's/Fields/fields/g' < SoItkDataPointSet.h > SoItkDataPointSet.h2
perl -pe 's/Fields/fields/g' < SoItkDataTransform.h > SoItkDataTransform.h2
perl -pe 's/Fields/fields/g' < SoItkMFDataImage.h > SoItkMFDataImage.h2
perl -pe 's/Fields/fields/g' < SoItkSFDataArray.h > SoItkSFDataArray.h2
perl -pe 's/Fields/fields/g' < SoItkSFDataDecorator.h > SoItkSFDataDecorator.h2
perl -pe 's/Fields/fields/g' < SoItkSFDataImage.h > SoItkSFDataImage.h2
perl -pe 's/Fields/fields/g' < SoItkSFDataImageMetric.h > SoItkSFDataImageMetric.h2
perl -pe 's/Fields/fields/g' < SoItkSFDataInterpolator.h > SoItkSFDataInterpolator.h2
perl -pe 's/Fields/fields/g' < SoItkSFDataMatrix.h > SoItkSFDataMatrix.h2
perl -pe 's/Fields/fields/g' < SoItkSFDataNeighborhood.h > SoItkSFDataNeighborhood.h2
perl -pe 's/Fields/fields/g' < SoItkSFDataOptimizer.h > SoItkSFDataOptimizer.h2
perl -pe 's/Fields/fields/g' < SoItkSFDataPointSet.h > SoItkSFDataPointSet.h2
perl -pe 's/Fields/fields/g' < SoItkSFDataTransform.h > SoItkSFDataTransform.h2
perl -pe 's/Fields/fields/g' < SoItkSFNodeContainer.h > SoItkSFNodeContainer.h2
perl -pe 's/Fields/fields/g' < SoItkUtils.h > SoItkUtils.h2
