perl -pe 's/Engines/engines/g' < SbItkNodeContainer.h2 > SbItkNodeContainer.h
perl -pe 's/Engines/engines/g' < SoItkDataArray.h2 > SoItkDataArray.h
perl -pe 's/Engines/engines/g' < SoItkDataDecorator.h2 > SoItkDataDecorator.h
perl -pe 's/Engines/engines/g' < SoItkDataImage.h2 > SoItkDataImage.h
perl -pe 's/Engines/engines/g' < SoItkDataImageMetric.h2 > SoItkDataImageMetric.h
perl -pe 's/Engines/engines/g' < SoItkDataInterpolator.h2 > SoItkDataInterpolator.h
perl -pe 's/Engines/engines/g' < SoItkDataMatrix.h2 > SoItkDataMatrix.h
perl -pe 's/Engines/engines/g' < SoItkDataNeighborhood.h2 > SoItkDataNeighborhood.h
perl -pe 's/Engines/engines/g' < SoItkDataOptimizer.h2 > SoItkDataOptimizer.h
perl -pe 's/Engines/engines/g' < SoItkDataPointSet.h2 > SoItkDataPointSet.h
perl -pe 's/Engines/engines/g' < SoItkDataTransform.h2 > SoItkDataTransform.h
perl -pe 's/Engines/engines/g' < SoItkMFDataImage.h2 > SoItkMFDataImage.h
perl -pe 's/Engines/engines/g' < SoItkSFDataArray.h2 > SoItkSFDataArray.h
perl -pe 's/Engines/engines/g' < SoItkSFDataDecorator.h2 > SoItkSFDataDecorator.h
perl -pe 's/Engines/engines/g' < SoItkSFDataImage.h2 > SoItkSFDataImage.h
perl -pe 's/Engines/engines/g' < SoItkSFDataImageMetric.h2 > SoItkSFDataImageMetric.h
perl -pe 's/Engines/engines/g' < SoItkSFDataInterpolator.h2 > SoItkSFDataInterpolator.h
perl -pe 's/Engines/engines/g' < SoItkSFDataMatrix.h2 > SoItkSFDataMatrix.h
perl -pe 's/Engines/engines/g' < SoItkSFDataNeighborhood.h2 > SoItkSFDataNeighborhood.h
perl -pe 's/Engines/engines/g' < SoItkSFDataOptimizer.h2 > SoItkSFDataOptimizer.h
perl -pe 's/Engines/engines/g' < SoItkSFDataPointSet.h2 > SoItkSFDataPointSet.h
perl -pe 's/Engines/engines/g' < SoItkSFDataTransform.h2 > SoItkSFDataTransform.h
perl -pe 's/Engines/engines/g' < SoItkSFNodeContainer.h2 > SoItkSFNodeContainer.h
perl -pe 's/Engines/engines/g' < SoItkUtils.h2 > SoItkUtils.h
