cat SbXipCoordinateTransform.h emptyline.txt > SbXipCoordinateTransform.h2
cat SbXipDirtyFieldList.h emptyline.txt > SbXipDirtyFieldList.h2
cat SbXipImageAdaptor.h emptyline.txt > SbXipImageAdaptor.h2
cat SbXipImageFile.h emptyline.txt > SbXipImageFile.h2
cat SbXipImage.h emptyline.txt > SbXipImage.h2
cat SbXipThread.h emptyline.txt > SbXipThread.h2
cat SbXipThreadMutex.h emptyline.txt > SbXipThreadMutex.h2
cat SoMFVariant.h emptyline.txt > SoMFVariant.h2
cat SoSFVariant.h emptyline.txt > SoSFVariant.h2
cat SoXipActiveViewportElement.h emptyline.txt > SoXipActiveViewportElement.h2
cat SoXipClipPlaneElement.h emptyline.txt > SoXipClipPlaneElement.h2
cat SoXipCursor.h emptyline.txt > SoXipCursor.h2
cat SoXipData.h emptyline.txt > SoXipData.h2
cat SoXipDataImageElement.h emptyline.txt > SoXipDataImageElement.h2
cat SoXipDataImage.h emptyline.txt > SoXipDataImage.h2
cat SoXipExaminer.h emptyline.txt > SoXipExaminer.h2
cat SoXipImageTextElement.h emptyline.txt > SoXipImageTextElement.h2
cat SoXipKit.h emptyline.txt > SoXipKit.h2
cat SoXipLutElement.h emptyline.txt > SoXipLutElement.h2
cat SoXipMFData.h emptyline.txt > SoXipMFData.h2
cat SoXipMFDataImage.h emptyline.txt > SoXipMFDataImage.h2
cat SoXipMprActiveElement.h emptyline.txt > SoXipMprActiveElement.h2
cat SoXipMprLockElement.h emptyline.txt > SoXipMprLockElement.h2
cat SoXipMprPlaneElement.h emptyline.txt > SoXipMprPlaneElement.h2
cat SoXipMultiTextureElement.h emptyline.txt > SoXipMultiTextureElement.h2
cat SoXipPickRadiusElement.h emptyline.txt > SoXipPickRadiusElement.h2
cat SoXipPluginLoader.h emptyline.txt > SoXipPluginLoader.h2
cat SoXipRenderModeElement.h emptyline.txt > SoXipRenderModeElement.h2
cat SoXipSFData.h emptyline.txt > SoXipSFData.h2
cat SoXipSFDataImage.h emptyline.txt > SoXipSFDataImage.h2
cat SoXipSubData.h emptyline.txt > SoXipSubData.h2
cat SoXipSubKit.h emptyline.txt > SoXipSubKit.h2
cat SoXipThreadManager.h emptyline.txt > SoXipThreadManager.h2
cat SoXipThreadQueueSensor.h emptyline.txt > SoXipThreadQueueSensor.h2
cat SoXipTransparentGeometryGroupElement.h emptyline.txt > SoXipTransparentGeometryGroupElement.h2
cat SoXipVolDataElement.h emptyline.txt > SoXipVolDataElement.h2
cat SoXipVolGroupElement.h emptyline.txt > SoXipVolGroupElement.h2
cat XipGeomUtils.h emptyline.txt > XipGeomUtils.h2
cat XipInventorUtils.h emptyline.txt > XipInventorUtils.h2
cat xipivcore.h emptyline.txt > xipivcore.h2
cat XipStringUtils.h emptyline.txt > XipStringUtils.h2
