mv SbXipCoordinateTransform.h2 SbXipCoordinateTransform.h
mv SbXipDirtyFieldList.h2 SbXipDirtyFieldList.h
mv SbXipImageAdaptor.h2 SbXipImageAdaptor.h
mv SbXipImageFile.h2 SbXipImageFile.h
mv SbXipImage.h2 SbXipImage.h
mv SbXipThread.h2 SbXipThread.h
mv SbXipThreadMutex.h2 SbXipThreadMutex.h
mv SoMFVariant.h2 SoMFVariant.h
mv SoSFVariant.h2 SoSFVariant.h
mv SoXipActiveViewportElement.h2 SoXipActiveViewportElement.h
mv SoXipClipPlaneElement.h2 SoXipClipPlaneElement.h
mv SoXipCursor.h2 SoXipCursor.h
mv SoXipData.h2 SoXipData.h
mv SoXipDataImageElement.h2 SoXipDataImageElement.h
mv SoXipDataImage.h2 SoXipDataImage.h
mv SoXipExaminer.h2 SoXipExaminer.h
mv SoXipImageTextElement.h2 SoXipImageTextElement.h
mv SoXipKit.h2 SoXipKit.h
mv SoXipLutElement.h2 SoXipLutElement.h
mv SoXipMFData.h2 SoXipMFData.h
mv SoXipMFDataImage.h2 SoXipMFDataImage.h
mv SoXipMprActiveElement.h2 SoXipMprActiveElement.h
mv SoXipMprLockElement.h2 SoXipMprLockElement.h
mv SoXipMprPlaneElement.h2 SoXipMprPlaneElement.h
mv SoXipMultiTextureElement.h2 SoXipMultiTextureElement.h
mv SoXipPickRadiusElement.h2 SoXipPickRadiusElement.h
mv SoXipPluginLoader.h2 SoXipPluginLoader.h
mv SoXipRenderModeElement.h2 SoXipRenderModeElement.h
mv SoXipSFData.h2 SoXipSFData.h
mv SoXipSFDataImage.h2 SoXipSFDataImage.h
mv SoXipSubData.h2 SoXipSubData.h
mv SoXipSubKit.h2 SoXipSubKit.h
mv SoXipThreadManager.h2 SoXipThreadManager.h
mv SoXipThreadQueueSensor.h2 SoXipThreadQueueSensor.h
mv SoXipTransparentGeometryGroupElement.h2 SoXipTransparentGeometryGroupElement.h
mv SoXipVolDataElement.h2 SoXipVolDataElement.h
mv SoXipVolGroupElement.h2 SoXipVolGroupElement.h
mv XipGeomUtils.h2 XipGeomUtils.h
mv XipInventorUtils.h2 XipInventorUtils.h
mv xipivcore.h2 xipivcore.h
mv XipStringUtils.h2 XipStringUtils.h
