mv FramebufferObject.h2 FramebufferObject.h
mv gpgpuContext.h2 gpgpuContext.h
mv gpgpuContext.h.old2 gpgpuContext.h.old
mv gpgpuContext.h.old22 gpgpuContext.h.old2
mv SoXipBufferMaskElement.h2 SoXipBufferMaskElement.h
mv SoXipCaptureImage.h2 SoXipCaptureImage.h
mv SoXipDepthTestElement.h2 SoXipDepthTestElement.h
mv SoXipDrawBuffersElement.h2 SoXipDrawBuffersElement.h
mv SoXipDrawImage.h2 SoXipDrawImage.h
mv SoXipDrawQuad.h2 SoXipDrawQuad.h
mv SoXipFboElement.h2 SoXipFboElement.h
mv SoXipFramebufferElement.h2 SoXipFramebufferElement.h
mv SoXipFramebufferFlip.h2 SoXipFramebufferFlip.h
mv SoXipFrameRate.h2 SoXipFrameRate.h
mv SoXipFrameRate.h.old2 SoXipFrameRate.h.old
mv SoXipGetTransform.h2 SoXipGetTransform.h
mv SoXipGlowElement.h2 SoXipGlowElement.h
mv SoXipGlowElement.h.old2 SoXipGlowElement.h.old
mv SoXipGLSLShaderProgramElement.h2 SoXipGLSLShaderProgramElement.h
mv SoXipMultiplyMatrices.h2 SoXipMultiplyMatrices.h
mv SoXipOffscreenRenderer.h2 SoXipOffscreenRenderer.h
mv SoXipOffscreenRenderer.h.old2 SoXipOffscreenRenderer.h.old
mv SoXipSetTransform.h2 SoXipSetTransform.h
mv SoXipShaderProgramElement.h2 SoXipShaderProgramElement.h
mv xipivcoregl.h2 xipivcoregl.h
