cat FramebufferObject.h ../core/emptyline.txt > FramebufferObject.h2
cat gpgpuContext.h ../core/emptyline.txt > gpgpuContext.h2
cat gpgpuContext.h.old ../core/emptyline.txt > gpgpuContext.h.old2
cat gpgpuContext.h.old2 ../core/emptyline.txt > gpgpuContext.h.old22
cat SoXipBufferMaskElement.h ../core/emptyline.txt > SoXipBufferMaskElement.h2
cat SoXipCaptureImage.h ../core/emptyline.txt > SoXipCaptureImage.h2
cat SoXipDepthTestElement.h ../core/emptyline.txt > SoXipDepthTestElement.h2
cat SoXipDrawBuffersElement.h ../core/emptyline.txt > SoXipDrawBuffersElement.h2
cat SoXipDrawImage.h ../core/emptyline.txt > SoXipDrawImage.h2
cat SoXipDrawQuad.h ../core/emptyline.txt > SoXipDrawQuad.h2
cat SoXipFboElement.h ../core/emptyline.txt > SoXipFboElement.h2
cat SoXipFramebufferElement.h ../core/emptyline.txt > SoXipFramebufferElement.h2
cat SoXipFramebufferFlip.h ../core/emptyline.txt > SoXipFramebufferFlip.h2
cat SoXipFrameRate.h ../core/emptyline.txt > SoXipFrameRate.h2
cat SoXipFrameRate.h.old ../core/emptyline.txt > SoXipFrameRate.h.old2
cat SoXipGetTransform.h ../core/emptyline.txt > SoXipGetTransform.h2
cat SoXipGlowElement.h ../core/emptyline.txt > SoXipGlowElement.h2
cat SoXipGlowElement.h.old ../core/emptyline.txt > SoXipGlowElement.h.old2
cat SoXipGLSLShaderProgramElement.h ../core/emptyline.txt > SoXipGLSLShaderProgramElement.h2
cat SoXipMultiplyMatrices.h ../core/emptyline.txt > SoXipMultiplyMatrices.h2
cat SoXipOffscreenRenderer.h ../core/emptyline.txt > SoXipOffscreenRenderer.h2
cat SoXipOffscreenRenderer.h.old ../core/emptyline.txt > SoXipOffscreenRenderer.h.old2
cat SoXipSetTransform.h ../core/emptyline.txt > SoXipSetTransform.h2
cat SoXipShaderProgramElement.h ../core/emptyline.txt > SoXipShaderProgramElement.h2
cat xipivcoregl.h ../core/emptyline.txt > xipivcoregl.h2
