mv SoSFVtkAlgorithmOutput.cpp2 SoSFVtkAlgorithmOutput.cpp
mv SoSFVtkObject.cpp2 SoSFVtkObject.cpp
mv SoVtkActor2D.cpp2 SoVtkActor2D.cpp
mv SoVtkActor2D.h2 SoVtkActor2D.h
mv SoVtkActor.cpp2 SoVtkActor.cpp
mv SoVtkActor.h2 SoVtkActor.h
mv SoVtkAlgorithmOutput.cpp2 SoVtkAlgorithmOutput.cpp
mv SoVtkAssembly.cpp2 SoVtkAssembly.cpp
mv SoVtkAssembly.h2 SoVtkAssembly.h
mv SoVtkConvertXipImageToVtkAlgorithmOutput.cpp2 SoVtkConvertXipImageToVtkAlgorithmOutput.cpp
mv SoVtkConvertXipImageToVtkAlgorithmOutput.h2 SoVtkConvertXipImageToVtkAlgorithmOutput.h
mv SoVtkImageActor.cpp2 SoVtkImageActor.cpp
mv SoVtkImageActor.h2 SoVtkImageActor.h
mv SoVtkImageViewer2.cpp2 SoVtkImageViewer2.cpp
mv SoVtkImageViewer2.h2 SoVtkImageViewer2.h
mv SoVtkLODActor.cpp2 SoVtkLODActor.cpp
mv SoVtkLODActor.h2 SoVtkLODActor.h
mv SoVtkMatrix4x4.cpp2 SoVtkMatrix4x4.cpp
mv SoVtkMatrix4x4.h2 SoVtkMatrix4x4.h
mv SoVtkObject.cpp2 SoVtkObject.cpp
mv SoVtkPolyData.cpp2 SoVtkPolyData.cpp
mv SoVtkPolyData.h2 SoVtkPolyData.h
mv SoVtkRenderer.cpp2 SoVtkRenderer.cpp
mv SoVtkRenderer.h2 SoVtkRenderer.h
mv SoVtkUtils.h2 SoVtkUtils.h
mv SoVtkVolume.cpp2 SoVtkVolume.cpp
mv SoVtkVolume.h2 SoVtkVolume.h
mv xipivvtk.cpp2 xipivvtk.cpp
