cat SoSFVtkAlgorithmOutput.cpp generated/emptyline.txt > SoSFVtkAlgorithmOutput.cpp2
cat SoSFVtkObject.cpp generated/emptyline.txt > SoSFVtkObject.cpp2
cat SoVtkActor2D.cpp generated/emptyline.txt > SoVtkActor2D.cpp2
cat SoVtkActor2D.h generated/emptyline.txt > SoVtkActor2D.h2
cat SoVtkActor.cpp generated/emptyline.txt > SoVtkActor.cpp2
cat SoVtkActor.h generated/emptyline.txt > SoVtkActor.h2
cat SoVtkAlgorithmOutput.cpp generated/emptyline.txt > SoVtkAlgorithmOutput.cpp2
cat SoVtkAssembly.cpp generated/emptyline.txt > SoVtkAssembly.cpp2
cat SoVtkAssembly.h generated/emptyline.txt > SoVtkAssembly.h2
cat SoVtkConvertXipImageToVtkAlgorithmOutput.cpp generated/emptyline.txt > SoVtkConvertXipImageToVtkAlgorithmOutput.cpp2
cat SoVtkConvertXipImageToVtkAlgorithmOutput.h generated/emptyline.txt > SoVtkConvertXipImageToVtkAlgorithmOutput.h2
cat SoVtkImageActor.cpp generated/emptyline.txt > SoVtkImageActor.cpp2
cat SoVtkImageActor.h generated/emptyline.txt > SoVtkImageActor.h2
cat SoVtkImageViewer2.cpp generated/emptyline.txt > SoVtkImageViewer2.cpp2
cat SoVtkImageViewer2.h generated/emptyline.txt > SoVtkImageViewer2.h2
cat SoVtkLODActor.cpp generated/emptyline.txt > SoVtkLODActor.cpp2
cat SoVtkLODActor.h generated/emptyline.txt > SoVtkLODActor.h2
cat SoVtkMatrix4x4.cpp generated/emptyline.txt > SoVtkMatrix4x4.cpp2
cat SoVtkMatrix4x4.h generated/emptyline.txt > SoVtkMatrix4x4.h2
cat SoVtkObject.cpp generated/emptyline.txt > SoVtkObject.cpp2
cat SoVtkPolyData.cpp generated/emptyline.txt > SoVtkPolyData.cpp2
cat SoVtkPolyData.h generated/emptyline.txt > SoVtkPolyData.h2
cat SoVtkRenderer.cpp generated/emptyline.txt > SoVtkRenderer.cpp2
cat SoVtkRenderer.h generated/emptyline.txt > SoVtkRenderer.h2
cat SoVtkUtils.h generated/emptyline.txt > SoVtkUtils.h2
cat SoVtkVolume.cpp generated/emptyline.txt > SoVtkVolume.cpp2
cat SoVtkVolume.h generated/emptyline.txt > SoVtkVolume.h2
cat xipivvtk.cpp generated/emptyline.txt > xipivvtk.cpp2
